### ISSUE TITLE
Can't chain multiple find calls using Sizzle-less build

### ISSUE THREAD

**Issue by mlewand** [jquery/jquery#2466]
Looks like `uniqueSort` function is not resolved correctly when jQuery is builded without Sizzle dependency.

When I try to call chained `find` methods I'm getting following exception: `Uncaught TypeError: n.uniqueSort is not a function`

## TC

* Build jQuery with `grunt custom:-sizzle`
* Try to chain multiple `find` calls, e.g.

	```html
	<!doctype html>
	<html lang="en">
		<head>
			<title>title</title>
		</head>
		<body>
		<div>
		  foo
		</div>
			<div>
		  <span>bar</span>
		</div>
	
		<script src="dist/jquery.min.js"></script>
		<script>
		  console.log( $('div').find('span').length );
		</script>
		</body>
	</html>
	```

* An exception is thrown: `Uncaught TypeError: n.uniqueSort is not a function`.

It happens also with other calls, e.g. `$( 'div' ).has( 'span' )`.

Experienced with 84ccf26 and a2ae215.

**Comment by gibson042** [comment]
Confirmed; caused by e1090c3d2b2a988a5b41f1f1ed9f8d6dcae02200. We need selector-sizzle to define both `uniqueSort` and `unique`. @mlewand, would you like to open a pull request?

**Comment by gibson042** [comment]
Whoops, I see that you have without referencing this issue. I'll move discussion to gh-2467.

**Comment by mlewand** [comment]
Yes, you're right I've already made a PR for that. I believe it was already referenced as I've referenced this issue in PR description.

> mlewand referenced this issue an hour ago
