### ISSUE TITLE
jQuery upgrade issues: jQuery.fn is not working properly after upgraded from 1.6.4 to 1.12.4 getting $(...). ****** is not a function

### ISSUE THREAD

**Issue by ilapavuluri** [jquery/jquery#5040]
### Description ###

I am currently using jQuery 1.6.4, in the process of upgrade I moved to 1.12.4, I am adding some additional functions to jQuery like this:

jQuery.fn.xyz= function(g, b) {
......
} 

I tried jQuery.fn.extend as well, both are loading the given function, but again it is clearing them and at the time of usage I am getting:

 $(...). ****** is not a function, because at this time my function is not part of jQuery functions list.

usage:
$("#editor1234").xyz('val')

If I am back to old jQuery(1.6.4), it is working perfectly fine.
