### ISSUE TITLE
[jQuery 3.2.1, Internet Explorer, Edge] $.isPlainObject fails when passed object has been created in child browser window

### ISSUE THREAD

**Issue by andrew-ew** [jquery/jquery#3841]
I have a simple HTML page (lets say PAGE1) that opens new browser window using window.open() function and loads another HTML page (lets say PAGE2):
`newWindow = window.open(page2url, "Page2", "top=50, left=50, width=400, height=200, resizable=1");`

PAGE2 creates a simple object in its own window: `object2 = { property2: 'value2'};`
**Note** this object is created in child browser window.

Then when I try execute `$.isPlainObject(newWindow.object2);` in main browser window then the following error is thrown:
**_TypeError: Function.prototype.toString: 'this' is not a Function object_**

![isplainobjecterror](https://user-images.githubusercontent.com/10869858/32592735-2ecd948a-c536-11e7-8816-763ed10516e3.PNG)

This was working fine with jQuery 2.1.4 but stopped working in jQuery 3.2.1.

I was using the following versions of IE and Edge:
 - IE: 11.0.9600.18816 (update versions 11.0.47 (KB4040685))
 - Edge: 40.15063.674.0 (Microsoft EdgeHTML 15.15063)
 
Tested on Windows 7 and Windows 10.
FireFox and Google Chrome do not have this issue.

I have created a ZIP with simple demo that reproduces the issue. Attached ZIP contains Readme.txt with detailed instructions of how to reproduce the error.
[jQueryTest.zip](https://github.com/jquery/jquery/files/1456737/jQueryTest.zip)

**Slightly updated the sample demo:**
[jQueryTest_updated.zip](https://github.com/jquery/jquery/files/1456861/jQueryTest_updated.zip)

**Comment by timmywil** [comment]
Thanks for opening an issue. However, you can create test cases on https://jsfiddle.net or https://jsbin.com so there's no need for local files. This would make it easier for us to assess the issue.

**Comment by gibson042** [comment]
Confirmed at http://jsbin.com/lodaropaqi .
This seems like an Edge bug, and possibly an intentional one since it appears limited to `window.open` as opposed to iframe windows. What's going on is that the `toString` method of the parent window's _%FunctionPrototype%_ is rejecting the child window's `Object` function (the constructor of plain objects in the child realm) for not being a "Function object", which is contrary to the [ECMAScript specification](http://ecma-international.org/ecma-262/7.0/#sec-function.prototype.tostring) because it _is_ a built-in function object, just not one that inherits from the _%FunctionPrototype%_ of the parent realm.

Unfortunately, I don't think there's anything we can do without introducing more false positives.

**Comment by awbuboltz** [comment]
@andrew-ew, did you ever figure out a workaround to this issue?

Does anyone know if a bug ever submitted to Microsoft?

**Comment by andrew-ew** [comment]
@awbuboltz The only workaround I see is to substitute isPlainObject function with implementation from jQuery 2.1.4 which is working fine for the described case.
