### ISSUE TITLE
elem.getClientRects() is not function

### ISSUE THREAD

**Issue by viswachaithanyaP** [jquery/jquery#3992]
### Description ###
I'm facing this issue after upgrading my jquery from 1.12.3.js to 3.3.1.js. I'm testing this in Slimframework php

Uncaught TypeError: elem.getClientRects is not a function
    at jQuery.fn.init.offset (jquery-3.3.1.js:10020)
    at Tipsy.show (jquery.tipsy.js:36)
    at HTMLDocument.enter (jquery.tipsy.js:157)
    at HTMLDocument.dispatch (jquery-3.3.1.js:5183)
    at HTMLDocument.elemData.handle (jquery-3.3.1.js:4991)
    at Object.trigger (jquery-3.3.1.js:8249)
    at Object.simulate (jquery-3.3.1.js:8318)
    at HTMLDocument.handler (jquery-3.3.1.js:8352)
    at HTMLInputElement.trigger (jquery-3.3.1.js:5306)
    at Object.trigger (jquery-3.3.1.js:8214)

**Comment by mgol** [comment]
Please provide a test case on [JSFiddle](https://jsfiddle.net/) or [JS Bin](https://jsbin.com/) as the issue template requested.

**Comment by chrlvclaudiu** [comment]
Here's a link provided in stellar.js github issues page: https://jsfiddle.net/farkasimre/fo2pba5o/
Hope this helps.

**Comment by mgol** [comment]
This is a bug in the jQuery Stellar plugin; it's invoking `.offset()` on `window` which is not supported; see https://jquery.com/upgrade-guide/3.0/#breaking-change-invalid-input-to-the-offset-method

However, the plugin doesn't seem to be maintained anymore: https://github.com/markdalgleish/stellar.js

You need to fork it or change it to something else.
