### ISSUE TITLE
TypeError: elem.getClientRects is not a function

### ISSUE THREAD

**Issue by hellatan** [jquery/jquery#2804]
I ran into this issue after jquery@2.2.0 was installed during a unit test build:

- TypeError: elem.getClientRects is not a function
      at Array.jQuery.expr.filters.visible (site/node_modules/somepackage/node_modules/jquery/dist/jquery.js:8909:63)
      at site/node_modules/somepackage/node_modules/jquery/dist/jquery.js:2198:22
      at superMatcher (site/node_modules/somepackage/node_modules/jquery/dist/jquery.js:2419:12)
      at Sizzle.select (site/node_modules/somepackage/node_modules/jquery/dist/jquery.js:2599:44)
      at Sizzle (site/node_modules/somepackage/node_modules/jquery/dist/jquery.js:864:9)
      at Function.Sizzle.matches (site/node_modules/somepackage/node_modules/jquery/dist/jquery.js:1400:9)
      at Function.jQuery.filter (site/node_modules/somepackage/node_modules/jquery/dist/jquery.js:2764:15)
      at winnow (site/node_modules/somepackage/node_modules/jquery/dist/jquery.js:2744:18)
      at [object Object].jQuery.fn.extend.filter (site/node_modules/somepackage/node_modules/jquery/dist/jquery.js:2796:26)
      at Object.kickOffMethod (site/file.js:24:16)

note: `site/node_modules/somepackage` is an internal package so I just masked it with that path

When I install jquery@2.1.4, all of my unit tests pass.

I poked around at my source and i see it trying to use the `:visible` filter like so:

```js
$('selector:visible');
```
and it seems to be failing there.

**Comment by timmywil** [comment]
Thanks for opening an issue. Which environment are you testing in?

**Comment by hellatan** [comment]
this was in node@4.2.3. We are also using jsdom@~3.1.2.

**Comment by timmywil** [comment]
I see. It sounds like jsdom doesn't support `getClientRects`. However, all of our supported browsers do. I wonder if that is in the works in jsdom.

**Comment by hellatan** [comment]
thanks for looking into this so quickly @timmywil. I left a comment in a closed ticket in jsdom.

**Comment by xjamundx** [comment]
Also running into this. I'm wondering if there's any way the change can be reverted or hopefully `jsdom` can patch this quickly :-/

**Comment by dmethvin** [comment]
@xjamundx and @hellatan How are you installing jquery and jsdom? If these are direct npm dependencies you should be able to give a specific version via the `package.json` file.

**Comment by xjamundx** [comment]
Yeah solution for me was to stick to `1.11.3` in the package.json

**Comment by hellatan** [comment]
Ya, @dmethvin pegging jquery to ~2.1.4 for now works. It was a standard `npm install`

**Comment by mgol** [comment]
Can one of you report it to jsdom? They should just implement this API, the current maintainer said he's willing to implement things that are needed to not break jQuery.

**Comment by mgol** [comment]
Can one of you report it to jsdom and post a link to the bug report here? They should just implement this API, the current maintainer said he's willing to implement things that are needed to not break jQuery.

**Comment by cancerberoSgx** [comment]
this is also happening to me using envjs. Could you please fix it ?

**Comment by dmethvin** [comment]
@cancerberoSgx "this" was fixed several months ago in jsdom, unless you are referring to a different "this".

**Comment by alexandis** [comment]
Don't have idea what are you suggesting here... I'm now have this issue after upgrading to jquery 3.0.0 from 2.2.3 in my solution. Seems like i have to roll back until this is fixed...

**Comment by dmethvin** [comment]
I am suggesting you file a bug and include a simple test case showing the problem, rather than adding a comment to a closed issue. The error message may be the same but the cause could be completely different.

**Comment by alexandis** [comment]
OK, i wish i could, but how to create "simple test case", if i have a complex script? Is it possible to send some kind of stack trace from some tool?

**Comment by davidyell** [comment]
I've also this this same issue, with `3.2.1`

**Comment by dvdobrovolskiy** [comment]
Have this issue on 
jQuery UI - v1.12.1 - 2016-09-14
and 
jQuery JavaScript Library v3.3.1

2jquery.js:10020 Uncaught TypeError: elem.getClientRects is not a function
    at I.fn.init.offset (jquery.js:10020)
    at init.slotByElement (kendo.all.js:101946)
    at init.open (Управление:223)
    at init.trigger (kendo.all.js:124)
    at init._triggerEvent (kendo.all.js:42889)
    at init.open (kendo.all.js:42719)
    at init._showHandler (kendo.all.js:42846)
    at HTMLTableCellElement.proxy (jquery.js:10268)
    at HTMLDivElement.dispatch (jquery.js:5183)
    at HTMLDivElement.elemData.handle (jquery.js:4991)

**Comment by dmethvin** [comment]
https://www.google.com/search?q=jquery+ui+clientrects+is+not+a+function
