### ISSUE TITLE
JQuery 1.12.0 not working with UI Dialog plugin

### ISSUE THREAD

**Issue by drsskelkar** [jquery/jquery#2924]
Earlier I was comfortably using jquery UI dialog plugin with all versions of jquery prior to 1.12.0
as soon as I have upgraded jquery to 1.12.0 UI Dialog plugin stopped working.
It used to work very well with jquery 1.11.4
I get the the error: TypeError: $(...).dialog is not a function
My code has not changed in any way
$("#TIMEOUT").dialog({autoOpen:false, modal:true, width:450, height:300});

**Comment by yashdeeph709** [comment]
Can you please give a plunk

**Comment by yashdeeph709** [comment]
I have create the same on codepen as well as locally can't get the issue
Please give some more detail and a code snippet.

**Comment by drsskelkar** [comment]
Tomorrow I will send you html pages which shows the issue as I have left my
work place.

On Monday, February 15, 2016, Yashdeep Hinge <notifications@github.com>
wrote:

> Can you please give a plunk
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jquery/jquery/issues/2924#issuecomment-184235726>.
>


-- 
Thank and regards,
Dr. Sharad Kelkar (+919825022004)

**Comment by timmywil** [comment]
Thanks. Please file an issue with a small test case on https://bugs.jqueryui.com/.

**Comment by drsskelkar** [comment]
The problem was related to incompatibility between jquery 1.12.0 and
migrate plugin 1.2.1
It was resolved when migrate plugin was changed to 1.3.0
There is no issue with jquery itself, it simply required proper version of
migrate plugin
