### ISSUE TITLE
QtWebKit: jQuery thinks that DOM elements collection is a function

### ISSUE THREAD

**Issue by natipo** [jquery/jquery#4756]
### Description ###
After upgrade from jQuery 3.2.1 to 3.3.0 [wkhtmltopdf ](https://wkhtmltopdf.org/index.html) tool stopped working due to the following error in jQuery:
```javascript
TypeError: 'undefined' is not a function (evaluating 'e.getAttribute("type")')
```

Browser to reproduce: QtWeb 3.8.5 (http://www.qtweb.net/)

The actual problem is inside `isFunction( obj )`. The current fix for web browsers where DOM nodes are being classified as a function is not enough for QtWebKit because types such as `NodeList` or `HTMLCollection` don't have attribute `nodeType` and the `typeof` command returns `function`.

Output using QtWeb JavaScript console:
```javascript
> typeof document.getElementsByTagName("p")
"function"
> document.getElementsByTagName("p").nodeType
undefined
> document.getElementsByTagName("p").toString()
"[object NodeList]"
```
Many systems depend on this wkhtmltopdf tool in terms of converting HTML page to PDF. Since jQuery 4 is about to drop support for old browsers, I would like to bring back support for QtWebKit 4 in jQuery 3.x so I could upgrade the system to the latest and secure version of jQuery 3.x.

### Link to test case ###

1. Create a simple index.html page.
```html
<!DOCTYPE html>
<html>
	<head>
		<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		<script type="text/javascript">
			$( document ).ready(function() {				
				$( "p" ).append( "<p>My second paragraph.</p>" );
			});
		</script>
	</head> 
	<body>
		<h1>My First Heading</h1>
		<p>My first paragraph.</p>
	</body>
</html>
```
2. Download portable version of QtWeb 3.8.5 (http://www.qtweb.net/download.html)
3. Open above page in QtWeb and notice that second paragraph tag is not added, but it should be.
4. Additionally you may enable console in QtWeb `Tools -> Enable Web Inspector` in order to see error details.

**Comment by mgol** [comment]
Thanks for the report. We don't support QtWebKit but I'm not opposed to a simple patch just for the `3.x` line if it's all that's needed.

For reference, the commit that caused this issue is a16339b8933f115da3661f3d3f64854c3fa60bdc. See the linked issues for an explanation about the change.

**Comment by mgol** [comment]
Fixed by #4757.
