### ISSUE TITLE
JQuery 2.2.0 popup issue

### ISSUE THREAD

**Issue by Zeni241** [jquery/jquery#2936]
I am trying to use basic pop up with JQuery mobile 1.4.5.
If I use JQuery version 2.2.0, I get the following error bellow.
But If I replace JQuery version 2.2.0 with JQuery version 2.1.4, everything works fine.

  Error with JQuery version 2.2.0
Uncaught TypeError: a.preventDefault is not a functionn.Event.preventDefault @ jquery-2.2.0.min.js:3n.Event.preventDefault @ jquery-2.2.0.min.js:3(anonymous function) @ jquery.mobile-1.4.5.js:11175e @ jquery-2.2.0.min.js:3n.event.dispatch @ jquery-2.2.0.min.js:3r.handle @ jquery-2.2.0.min.js:3n.extend.trigger @ jquery-2.2.0.min.js:4(anonymous function) @ jquery-2.2.0.min.js:4n.extend.each @ jquery-2.2.0.min.js:2n.fn.n.each @ jquery-2.2.0.min.js:2n.fn.extend.trigger @ jquery-2.2.0.min.js:4$.event.special.navigate.self.popstate @ jquery.mobile-1.4.5.js:2279n.event.dispatch @ jquery-2.2.0.min.js:3r.handle @ jquery-2.2.0.min.js:3n.extend.trigger @ jquery-2.2.0.min.js:4(anonymous function) @ jquery-2.2.0.min.js:4n.extend.each @ jquery-2.2.0.min.js:2n.fn.n.each @ jquery-2.2.0.min.js:2n.fn.extend.trigger @ jquery-2.2.0.min.js:4$.extend.go @ jquery.mobile-1.4.5.js:3043$.mobile.navigate @ jquery.mobile-1.4.5.js:3205$.widget.open @ jquery.mobile-1.4.5.js:11181(anonymous function) @ jquery.mobile-1.4.5.js:835(anonymous function) @ jquery.mobile-1.4.5.js:933n.extend.each @ jquery-2.2.0.min.js:2n.fn.n.each @ jquery-2.2.0.min.js:2$.fn.(anonymous function) @ jquery.mobile-1.4.5.js:919$.mobile.popup.handleLink @ jquery.mobile-1.4.5.js:11217(anonymous function) @ jquery.mobile-1.4.5.js:11234n.event.dispatch @ jquery-2.2.0.min.js:3r.handle @ jquery-2.2.0.min.js:3n.extend.trigger @ jquery-2.2.0.min.js:4(anonymous function) @ jquery-2.2.0.min.js:4n.extend.each @ jquery-2.2.0.min.js:2n.fn.n.each @ jquery-2.2.0.min.js:2n.fn.extend.trigger @ jquery-2.2.0.min.js:4$.widget._triggerWithDeprecated @ jquery.mobile-1.4.5.js:5020(anonymous function) @ jquery.mobile-1.4.5.js:835$.widget._triggerPageBeforeChange @ jquery.mobile-1.4.5.js:5418(anonymous function) @ jquery.mobile-1.4.5.js:835$.widget.change @ jquery.mobile-1.4.5.js:5445(anonymous function) @ jquery.mobile-1.4.5.js:835(anonymous function) @ jquery.mobile-1.4.5.js:933n.extend.each @ jquery-2.2.0.min.js:2n.fn.n.each @ jquery-2.2.0.min.js:2$.fn.(anonymous function) @ jquery.mobile-1.4.5.js:919$.mobile.changePage @ jquery.mobile-1.4.5.js:5844(anonymous function) @ jquery.mobile-1.4.5.js:6133n.event.dispatch @ jquery-2.2.0.min.js:3r.handle @ jquery-2.2.0.min.js:3

Following is my page markup:
```
<head>
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="../scripts/jquerymobile/jquery.mobile-1.4.5.min.css" rel="stylesheet" />
    <script src="../scripts/jquery-2.1.4.min.js"></script>
    <!--<script src="../scripts/jquery-2.2.0.min.js"></script>-->
    <script src="../scripts/jquerymobile/jquery.mobile-1.4.5.js"></script>
</head>
<body>
    <div data-role="page">
        <div data-role="header">...</div>
        <div role="main" class="ui-content">
            ...
            <a href="#popupBasic" data-rel="popup" class="ui-btn ui-corner-all ui-shadow ui-btn-inline" data-transition="pop">Basic Popup</a>
            <div data-role="popup" id="popupBasic">
                <p>This is a completely basic popup, no options set.</p>
            </div>
        </div>
        <div data-role="footer">...</div>
    </div>

</body>
```

**Comment by timmywil** [comment]
Thanks for opening an issue. Please provide a test case from http://jsfiddle.net to help us assess the problem.

**Comment by dmethvin** [comment]
I'm pretty sure this is a dup of #2917 so I'll close it.

**Comment by afable** [comment]
I am getting the same issue right now when setting up a basic pop up with JQuery mobile 1.4.5 and JQuery version 2.2.4.

But If I replace JQuery version 2.2.4 with JQuery version 2.1.4, everything works fine.

**Comment by grisson2** [comment]
Same for me. JQuery>=2.2.0 with JQueryMobile 1.4.5 give me 'a.preventDefault is not a function'
Works with jquery 2.1.4
