### ISSUE TITLE
Setup code for working in Node environment doesn't work with jsdom version ^15.2.1

### ISSUE THREAD

**Issue by mrdulin** [jquery/jquery#4546]
### Description ###

Setup code for working in Node environment doesn't work with jsdom version `^15.2.1`
The npm package link: https://www.npmjs.com/package/jquery#node

```js
require("jsdom").env("", function(err, window) {
    if (err) {
        console.error(err);
        return;
    }
 
    var $ = require("jquery")(window);
});
```

Got error:

```bash
require("jsdom").env("", function(err, window) {
                 ^
TypeError: require(...).env is not a function
...
```

### Dependencies versions ###

```json
"jsdom": "^15.2.1",
"jquery": "^3.4.1",
```
node version: v10.16.0
npm version: 6.12.0
os: macOS 10.13.6 (17G6030)

Please update the setup code for Node.

**Comment by mgol** [comment]
Thanks for the report, we'll update it for the new jQuery version (this was an older JSDOM syntax).

For now, this is the way of using newest JSDOM with jQuery:
```js
const { JSDOM } = require( "jsdom" );
const { window } = new JSDOM( "" );
const $ = require( "jquery" )( window );
```

**Comment by mrdulin** [comment]
@mgol Thanks. It works fine now.

**Comment by mgol** [comment]
PR: https://github.com/jquery/jquery-dist/pull/5
